In [5]:
import pandas as pd
import numpy as np

In [6]:
index = pd.date_range('1/1/2000', periods=8)
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [7]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a   -0.587470
b   -0.604373
c   -0.515685
d    0.378900
e    1.334518
dtype: float64

In [8]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=['A', 'B', 'C'])
df

A         B         C
2000-01-01 -1.272221  0.418852 -1.218567
2000-01-02  0.835774 -1.147240 -0.228105
2000-01-03  2.158136  0.820745  0.536409
2000-01-04 -0.688194 -0.888111 -2.439370
2000-01-05  1.265778 -2.216098 -1.161154
2000-01-06  0.887465 -0.159919  1.242937
2000-01-07 -0.122640  0.437131  0.223426
2000-01-08  2.718050 -1.979806 -1.578829

In [9]:
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],
              major_axis=pd.date_range('1/1/2000', periods=5),
              minor_axis=['A', 'B', 'C', 'D'])
wp

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:3265: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [10]:
long_series = pd.Series(np.random.randn(1000))
long_series.head()

0   -1.028350
1   -0.871444
2   -0.140905
3    0.409926
4   -0.084416
dtype: float64

In [11]:
long_series.tail(3)

997    0.118752
998    1.187711
999    0.108269
dtype: float64

In [12]:
df[:2]

A         B         C
2000-01-01 -1.272221  0.418852 -1.218567
2000-01-02  0.835774 -1.147240 -0.228105

In [14]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01 -1.272221  0.418852 -1.218567
2000-01-02  0.835774 -1.147240 -0.228105
2000-01-03  2.158136  0.820745  0.536409
2000-01-04 -0.688194 -0.888111 -2.439370
2000-01-05  1.265778 -2.216098 -1.161154
2000-01-06  0.887465 -0.159919  1.242937
2000-01-07 -0.122640  0.437131  0.223426
2000-01-08  2.718050 -1.979806 -1.578829

In [15]:
s.array

<PandasArray>
[-0.5874698341211232,  -0.604372586470277, -0.5156845546303224,
  0.3788999864549819,  1.3345182754057945]
Length: 5, dtype: float64

In [16]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [17]:
s.to_numpy()

array([-0.58746983, -0.60437259, -0.51568455,  0.37889999,  1.33451828])

In [18]:
np.asarray(s)

array([-0.58746983, -0.60437259, -0.51568455,  0.37889999,  1.33451828])

In [19]:
ser = pd.Series(pd.date_range('2000', periods=2, tz="CET"))
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [20]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [21]:
df.to_numpy()

array([[-1.27222141,  0.41885187, -1.2185672 ],
       [ 0.83577387, -1.14724023, -0.22810495],
       [ 2.15813585,  0.82074532,  0.53640894],
       [-0.68819396, -0.88811118, -2.43937001],
       [ 1.26577796, -2.21609848, -1.16115399],
       [ 0.88746525, -0.15991855,  1.24293687],
       [-0.12263998,  0.43713113,  0.22342577],
       [ 2.71805045, -1.97980551, -1.57882916]])

In [22]:
pd.set_option('compute.use_bottleneck', False)
pd.set_option('compute.use_numexpr', False)

In [23]:
df = pd.DataFrame({
    'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
    'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
    'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])
})
df

one     three       two
a  0.444942       NaN  2.187361
b  0.118148 -1.071401 -0.399816
c  1.187781 -0.561913  1.934021
d       NaN -2.389601 -1.707896

In [24]:
row = df.iloc[1]
column = df['two']
df.sub(row, axis='columns')

one     three       two
a  0.326794       NaN  2.587177
b  0.000000  0.000000  0.000000
c  1.069634  0.509488  2.333837
d       NaN -1.318200 -1.308080

In [25]:
df.sub(row, axis=1)

one     three       two
a  0.326794       NaN  2.587177
b  0.000000  0.000000  0.000000
c  1.069634  0.509488  2.333837
d       NaN -1.318200 -1.308080

In [26]:
df.sub(row, axis='index')

one  three  two
a      NaN    NaN  NaN
b      NaN    NaN  NaN
c      NaN    NaN  NaN
d      NaN    NaN  NaN
one    NaN    NaN  NaN
three  NaN    NaN  NaN
two    NaN    NaN  NaN